"""
build_source_data.py

Author:    Nikash Umesh (github.com/numesh4)
Project:   multi-touch-attribution-dbt
Created:   2026
License:   MIT (see LICENSE in the project root)

------------------------------------------------------------------------
ALL SYNTHETIC DATA GENERATED BY THIS SCRIPT WAS CREATED BY NIKASH UMESH.
------------------------------------------------------------------------
Every value produced here (users, touchpoints, calls, emails, orders,
costs) is randomly generated for demonstration purposes only. No real
customer, financial, or platform data is used or referenced anywhere in
this script or its output. The generation logic, schema design, and
scenario modeling are original work created by the author for this
project.

Loads synthetic marketing attribution data directly into DuckDB as raw
schemas, each standing in for a different real-world source system that
would normally be landed by an EL tool (Fivetran, Airbyte, or a custom API
extract script), not by dbt.

Schemas / tables:
    raw_ga4.events                   <- GA4 / Segment export      (paid_search, email, organic touches)
    raw_meta_pixel.events            <- Meta Pixel / Conversions API export (paid_social touches)
    raw_callrail.calls               <- Call tracking export      (phone touches)
    raw_helpdesk.inbound_emails      <- Helpdesk / support inbox export (email_inbound touches)
    raw_shopify.orders               <- Shopify / orders DB export (conversions)
    raw_shopify.customers            <- Shopify / CRM customer export (B2B/B2C segment, phone, email)
    raw_google_ads.campaign_costs    <- Google Ads API export     (paid_search costs)
    raw_meta_ads.ad_insights         <- Meta Ads API export       (paid_social costs)

Six channels now: paid_search, paid_social, email, organic, phone, email_inbound.
Each channel's touchpoints land in a DIFFERENT raw table, matching how these
systems actually work in production, none of them share a schema, and two
of them (calls, inbound emails) don't even share a clean user_id, they're
matched by phone number / email address instead, a deliberately realistic
join challenge for the staging layer (mirrors real-world identity resolution,
same idea as the GA4/Shopify user_id caveat already documented).

Run with:  python build_source_data.py
Requires: dev.duckdb to already exist (run `dbt debug` at least once first),
and this script run from the project root, same folder as dbt_project.yml.
"""

import random
from datetime import datetime, timedelta
from pathlib import Path

import duckdb
import pandas as pd

__author__ = "Nikash Umesh"
__github__ = "https://github.com/numesh4"
__license__ = "MIT"

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

random.seed(42)

DB_PATH = Path("dev.duckdb")    # path to the DuckDB database file, relative to the project root; 
                                #all data will be loaded directly into this database, bypassing dbt seed; 
                                # added to gitignore so it doesn't get checked in, since it's a binary file that will change every time this script is run

N_USERS = 30000 # unique users to generate (B2C + B2B combined), adjust as needed for performance / runtime  
CHANNELS = ["paid_search", "paid_social", "email", "organic", "phone", "email_inbound"]

START_DATE = datetime(2025, 7, 1)
END_DATE = datetime(2026, 6, 30)

CUSTOMER_TYPE_WEIGHTS = {"b2c": 0.85, "b2b": 0.15}

SCENARIO_WEIGHTS_B2C = {
    "single_touch": 0.35,
    "multi_touch": 0.35,
    "non_converting": 0.20,
    "repeat_purchaser": 0.08,
    "long_gap": 0.02,
}
SCENARIO_WEIGHTS_B2B = {
    "single_touch": 0.10,
    "multi_touch": 0.35,
    "non_converting": 0.20,
    "repeat_purchaser": 0.15,
    "long_gap": 0.20,
}

# B2B skews toward phone/email_inbound (sales calls, inquiries) and away
# from paid_social; B2C skews toward the web/paid channels.
CHANNEL_WEIGHTS_B2C = {
    "paid_search": 0.30, "paid_social": 0.30, "email": 0.12,
    "organic": 0.15, "phone": 0.05, "email_inbound": 0.08,
}
CHANNEL_WEIGHTS_B2B = {
    "paid_search": 0.32, "paid_social": 0.06, "email": 0.20,
    "organic": 0.17, "phone": 0.15, "email_inbound": 0.10,
}

CAMPAIGNS_BY_CHANNEL = {
    "paid_search": ["brand_search", "generic_search", "competitor_search"],
    "paid_social": ["prospecting_ig", "retargeting_fb", "lookalike_tiktok"],
    "email": ["newsletter", "abandoned_cart", "win_back"],
    "organic": ["blog", "direct", "referral"],
    "phone": ["inbound_sales_line", "support_callback", "click_to_call_ad"],
    "email_inbound": ["product_inquiry", "support_request", "sales_question"],
}

CHANNEL_BASE_DAILY_SPEND = {
    "paid_search": 450,
    "paid_social": 380,
    "email": 40,
    "organic": 0,
}

REVENUE_RANGE_B2C = (35, 420)
REVENUE_RANGE_B2B = (800, 6000)

TRACKING_PHONE_NUMBER = "+1-800-555-0199"  # the business's call-tracking number


def random_date(start, end):
    delta_days = (end - start).days
    return start + timedelta(days=random.randint(0, delta_days), seconds=random.randint(0, 86399))


def weighted_channel_choice(customer_type):
    weights = CHANNEL_WEIGHTS_B2B if customer_type == "b2b" else CHANNEL_WEIGHTS_B2C
    channels, w = zip(*weights.items())
    return random.choices(channels, weights=w)[0]


def assign_scenario(customer_type):
    weights = SCENARIO_WEIGHTS_B2B if customer_type == "b2b" else SCENARIO_WEIGHTS_B2C
    scenarios, w = zip(*weights.items())
    return random.choices(scenarios, weights=w)[0]


def assign_customer_type():
    types, w = zip(*CUSTOMER_TYPE_WEIGHTS.items())
    return random.choices(types, weights=w)[0]


def revenue_for(customer_type):
    lo, hi = REVENUE_RANGE_B2B if customer_type == "b2b" else REVENUE_RANGE_B2C
    return round(random.uniform(lo, hi), 2)


def fake_phone(user_num):
    return f"+1-555-{100 + (user_num % 800):03d}-{1000 + (user_num * 7) % 9000:04d}"


def fake_email(user_num, customer_type):
    domain = "acmecorp-example.com" if customer_type == "b2b" else "example.com"
    return f"customer{user_num:05d}@{domain}"


# ---------------------------------------------------------------------------
# Per-channel touchpoint recording, routes to the correct raw source table
# ---------------------------------------------------------------------------

ga4_events = []
meta_pixel_events = []
callrail_calls = []
helpdesk_emails = []

_ga4_id = [1]
_meta_pixel_id = [1]
_call_id = [1]
_ticket_id = [1]


def record_touchpoint(channel, campaign, ts, customer_id, phone, email):
    if channel in ("paid_search", "email", "organic"):
        ga4_events.append((_ga4_id[0], customer_id, channel, campaign, ts))
        _ga4_id[0] += 1
    elif channel == "paid_social":
        # Meta's own pixel firing for social touches, tracked independently
        # of GA4, using Meta's naming convention (fb_external_id rather than
        # ga_user_id) even though it resolves to the same customer here
        meta_pixel_events.append((_meta_pixel_id[0], customer_id, campaign, ts))
        _meta_pixel_id[0] += 1
    elif channel == "phone":
        duration = random.randint(30, 600)
        callrail_calls.append((_call_id[0], TRACKING_PHONE_NUMBER, phone, ts, duration, "inbound", campaign))
        _call_id[0] += 1
    elif channel == "email_inbound":
        helpdesk_emails.append((_ticket_id[0], email, ts, campaign))
        _ticket_id[0] += 1


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

conversions = []
customers = []
conversion_id_counter = 1

for user_num in range(1, N_USERS + 1):
    user_id = f"user_{user_num:05d}"
    customer_type = assign_customer_type()
    phone = fake_phone(user_num)
    email = fake_email(user_num, customer_type)
    customers.append((user_id, customer_type, random_date(START_DATE, END_DATE).date(), phone, email))

    scenario = assign_scenario(customer_type)

    if scenario == "single_touch":
        touch_date = random_date(START_DATE, END_DATE - timedelta(days=2))
        channel = weighted_channel_choice(customer_type)
        campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
        record_touchpoint(channel, campaign, touch_date, user_id, phone, email)
        convert_date = touch_date + timedelta(hours=random.randint(1, 48))
        conversions.append((conversion_id_counter, user_id, convert_date, revenue_for(customer_type)))
        conversion_id_counter += 1

    elif scenario == "multi_touch":
        n_touches = random.randint(3, 8)    # number of touches before conversion
        window_days = random.randint(3, 21)
        journey_start = random_date(START_DATE, END_DATE - timedelta(days=window_days + 3))
        touch_dates = sorted(journey_start + timedelta(days=random.uniform(0, window_days))
                              for _ in range(n_touches))
        for td in touch_dates:
            channel = weighted_channel_choice(customer_type)
            campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
            record_touchpoint(channel, campaign, td, user_id, phone, email)
        convert_date = touch_dates[-1] + timedelta(hours=random.randint(1, 72))
        conversions.append((conversion_id_counter, user_id, convert_date, revenue_for(customer_type)))
        conversion_id_counter += 1

    elif scenario == "non_converting":
        n_touches = random.randint(1, 4) # number of touches without conversion
        for _ in range(n_touches):
            td = random_date(START_DATE, END_DATE)
            channel = weighted_channel_choice(customer_type)
            campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
            record_touchpoint(channel, campaign, td, user_id, phone, email)

    elif scenario == "repeat_purchaser":
        n_touches = random.randint(2, 4)    # number of touches before first conversion
        window_days = random.randint(3, 14)
        journey_start = random_date(START_DATE, END_DATE - timedelta(days=180))
        touch_dates = sorted(journey_start + timedelta(days=random.uniform(0, window_days))
                              for _ in range(n_touches))
        for td in touch_dates:
            channel = weighted_channel_choice(customer_type)
            campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
            record_touchpoint(channel, campaign, td, user_id, phone, email)
        first_convert = touch_dates[-1] + timedelta(hours=random.randint(1, 72))
        conversions.append((conversion_id_counter, user_id, first_convert, revenue_for(customer_type)))
        conversion_id_counter += 1
        n_repeats = random.randint(1, 3)
        last_date = first_convert
        for _ in range(n_repeats):
            gap = timedelta(days=random.randint(20, 60))
            if last_date + gap >= END_DATE:
                break
            re_touch_date = last_date + gap - timedelta(days=random.randint(0, 2))
            channel = weighted_channel_choice(customer_type)
            campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
            record_touchpoint(channel, campaign, re_touch_date, user_id, phone, email)
            repeat_convert_date = last_date + gap
            conversions.append((conversion_id_counter, user_id, repeat_convert_date, revenue_for(customer_type)))
            conversion_id_counter += 1
            last_date = repeat_convert_date

    elif scenario == "long_gap":
        n_touches = random.randint(2, 5)    # number of touches before conversion
        window_days = random.randint(30, 90)
        journey_start = random_date(START_DATE, END_DATE - timedelta(days=window_days + 3))
        touch_dates = sorted(journey_start + timedelta(days=random.uniform(0, window_days))
                              for _ in range(n_touches))
        for td in touch_dates:
            channel = weighted_channel_choice(customer_type)
            campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
            record_touchpoint(channel, campaign, td, user_id, phone, email)
        convert_date = touch_dates[-1] + timedelta(hours=random.randint(1, 48))
        conversions.append((conversion_id_counter, user_id, convert_date, revenue_for(customer_type)))
        conversion_id_counter += 1

# same-day rapid touches overlay (web channels only, calls/inbound email
# don't realistically happen back-to-back the same way clicks do)
customer_lookup = {c[0]: c for c in customers}  # user_id -> (id, type, seen, phone, email)
web_user_ids = list({e[1] for e in ga4_events} | {e[1] for e in meta_pixel_events})
rapid_sample = random.sample(web_user_ids, k=int(len(web_user_ids) * 0.05)) if web_user_ids else []
for uid in rapid_sample:
    _, ctype, _, phone, email = customer_lookup[uid]
    base_date = random_date(START_DATE, END_DATE - timedelta(days=1))
    for _ in range(random.randint(2, 4)):
        channel = random.choice(["paid_search", "paid_social", "email", "organic"])
        campaign = random.choice(CAMPAIGNS_BY_CHANNEL[channel])
        same_day_time = base_date + timedelta(minutes=random.randint(0, 600))
        record_touchpoint(channel, campaign, same_day_time, uid, phone, email)

# ---------------------------------------------------------------------------
# Daily cost data, split by platform
# ---------------------------------------------------------------------------

google_ads_costs = []
meta_ads_costs = []
current_date = START_DATE
while current_date <= END_DATE:
    is_weekend = current_date.weekday() >= 5
    seasonal_multiplier = 1.4 if current_date.month in (11, 12) else 1.0
    weekend_multiplier = 0.7 if is_weekend else 1.0

    base = CHANNEL_BASE_DAILY_SPEND["paid_search"]
    spend = round(base * seasonal_multiplier * weekend_multiplier * random.uniform(0.85, 1.15), 2)
    google_ads_costs.append((current_date.date(), "paid_search", spend))

    base = CHANNEL_BASE_DAILY_SPEND["paid_social"]
    spend = round(base * seasonal_multiplier * weekend_multiplier * random.uniform(0.85, 1.15), 2)
    impressions = int(spend * random.uniform(180, 260))
    clicks = int(impressions * random.uniform(0.008, 0.02))
    meta_ads_costs.append((current_date.date(), "prospecting_ig_retargeting_fb_lookalike_tiktok",
                            spend, impressions, clicks))

    current_date += timedelta(days=1)

# ---------------------------------------------------------------------------
# Build DataFrames, matching realistic source-system column naming
# ---------------------------------------------------------------------------

df_events = pd.DataFrame(ga4_events, columns=[
    "event_id", "ga_user_id", "traffic_source", "campaign_name", "event_timestamp"
])

df_meta_pixel = pd.DataFrame(meta_pixel_events, columns=[
    "pixel_event_id", "fb_external_id", "campaign_name", "event_time"
])

df_calls = pd.DataFrame(callrail_calls, columns=[
    "call_id", "tracking_phone_number", "caller_phone_number",
    "call_datetime", "duration_seconds", "direction", "source_campaign"
])

df_inbound_emails = pd.DataFrame(helpdesk_emails, columns=[
    "ticket_id", "from_email", "received_at", "subject_category"
])

df_orders = pd.DataFrame(conversions, columns=[
    "order_id", "customer_id", "created_at", "total_price"
])

df_customers = pd.DataFrame(customers, columns=[
    "customer_id", "customer_type", "first_seen_date", "phone_number", "email"
])

df_google_costs = pd.DataFrame(google_ads_costs, columns=[
    "date", "channel_name", "cost_micros_equivalent"
])
df_google_costs["cost_micros_equivalent"] = (df_google_costs["cost_micros_equivalent"] * 1_000_000).astype("int64")

df_meta_costs = pd.DataFrame(meta_ads_costs, columns=[
    "date_start", "campaign_group", "spend", "impressions", "clicks"
])

# ---------------------------------------------------------------------------
# Load into DuckDB
# ---------------------------------------------------------------------------

con = duckdb.connect(str(DB_PATH))

for schema in ("raw_ga4", "raw_meta_pixel", "raw_callrail", "raw_helpdesk",
               "raw_shopify", "raw_google_ads", "raw_meta_ads"):
    con.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

con.execute("CREATE OR REPLACE TABLE raw_ga4.ga4events AS SELECT * FROM df_events")
con.execute("CREATE OR REPLACE TABLE raw_meta_pixel.meta_pixel_events AS SELECT * FROM df_meta_pixel")
con.execute("CREATE OR REPLACE TABLE raw_callrail.calls AS SELECT * FROM df_calls")
con.execute("CREATE OR REPLACE TABLE raw_helpdesk.inbound_helpdesk_emails AS SELECT * FROM df_inbound_emails")
con.execute("CREATE OR REPLACE TABLE raw_shopify.shopify_orders AS SELECT * FROM df_orders")
con.execute("CREATE OR REPLACE TABLE raw_shopify.customers AS SELECT * FROM df_customers")
con.execute("CREATE OR REPLACE TABLE raw_google_ads.google_campaign_costs AS SELECT * FROM df_google_costs")
con.execute("CREATE OR REPLACE TABLE raw_meta_ads.meta_ad_insights AS SELECT * FROM df_meta_costs")

con.close()

n_b2b = sum(1 for c in customers if c[1] == "b2b")
n_b2c = sum(1 for c in customers if c[1] == "b2c")
total_touchpoints = len(ga4_events) + len(meta_pixel_events) + len(callrail_calls) + len(helpdesk_emails)

print(f"Synthetic data generated by {__author__} ({__github__})")
print("All data below is randomly generated for demonstration purposes only.")
print()
print("Source data loaded directly into DuckDB (bypassing dbt seed).")
print(f"  Database:  {DB_PATH.resolve()}")
print()
print("  Touchpoint sources (4 tables, 4 different schemas):")
print(f"    raw_ga4.events                 : {len(df_events)} rows  (paid_search, email, organic)")
print(f"    raw_meta_pixel.events          : {len(df_meta_pixel)} rows  (paid_social)")
print(f"    raw_callrail.calls             : {len(df_calls)} rows  (phone)")
print(f"    raw_helpdesk.inbound_emails    : {len(df_inbound_emails)} rows  (email_inbound)")
print(f"    Total touchpoints across all sources: {total_touchpoints}")
print()
print("  Conversion / customer sources:")
print(f"    raw_shopify.orders             : {len(df_orders)} rows")
print(f"    raw_shopify.customers          : {len(df_customers)} rows  (b2c: {n_b2c}, b2b: {n_b2b})")
print()
print("  Cost sources:")
print(f"    raw_google_ads.campaign_costs  : {len(df_google_costs)} rows")
print(f"    raw_meta_ads.ad_insights       : {len(df_meta_costs)} rows")
print()
print("Next: update models/staging/_staging__sources.yml with meta_pixel, callrail, and helpdesk sources.")